[package]
name = "mba-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
num-traits = "0.2"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }